### ISSUE TITLE
Problems with point cloud data for open_drawer tasks

### ISSUE THREAD

**Issue by ljy1234-special** [arnold-benchmark/arnold#40]
Hi, I am in the process of debugging the `open_drawer` task and I found that the pcd obtained from the `act2` phase in some datasets is `nan` as shown below. (The example shows '`Ziheng-open_drawer-7-1-0.0-0.25-0-Mon_Jan_30_14:01:07_2023.npz`'). May I ask what is the reason for this?How did you solve it?
![image](https://github.com/user-attachments/assets/599e9351-8ed3-45f8-a458-5052de2b4fb2)
![image](https://github.com/user-attachments/assets/953e4eec-40ba-4884-ab9d-7584ffc9ee28)

**Comment by nikepupu** [comment]
Is it possible some depth is inf?

**Comment by ljy1234-special** [comment]
I found that the inf in the depth value can be eliminated after a clip operation, but the nan information remains.
![image](https://github.com/user-attachments/assets/69e02fa4-6c4e-41cc-940e-05f87af752a7)
![image](https://github.com/user-attachments/assets/dee499f1-e90d-4124-ba91-579f01cdee19)

**Comment by huangjy-pku** [comment]
Hello, @ljy1234-special ! I checked the file you mentioned and indeed encountered the issue you mentioned. This is caused by some `nan` elements in the raw camera sensory data `camera_obs['depthLinear']` and `np.clip` cannot handle `nan` (though it can handle `inf`). More specifically, this issue only exists in the second camera `camera_obs = imgs[1]` in the third keyframe `imgs = npz['gt'][3]['images']` for this npz file. Maybe some operations in the model input preprocess avoid the harm of `nan` so that we have not found such issues during our training.
