### ISSUE TITLE
Two-stage issues

### ISSUE THREAD

**Issue by ljy1234-special** [arnold-benchmark/arnold#42]
I see that your code sets different weights for the two stages when taking out the data. Could you please tell me if you take out both phases for training at the same time, then will it have any effect on the experimental results?

**Comment by huangjy-pku** [comment]
We set different weights for the two stages because multiple second-stage demos may correspond to one first-stage demo. For example, open drawer to 25%/50%/75% may share a first-stage action. To avoid the learning is biased towards the first-stage action, we re-balance the distribution for training. Though, we have not tried experiments with equal sampling weights.

**Comment by ljy1234-special** [comment]
Thank you！
